### ISSUE TITLE
Status of Chart.Zoom

### ISSUE THREAD

**Issue by nux17** [chartjs/chartjs-plugin-zoom#1]
Hey, good job for this feature :).

Is the plugin stable/production ready?

**Comment by etimberg** [comment]
@nux17 I don't think this is production ready but if you give it a try and like it I don't see why you couldn't use it.

**Comment by ddj116** [comment]
I'm kind of a javascript noob so I have a dumb question about the setup.  For Chart.js, I can go into samples/ and do 'firefox \<sample\>.html' and it all works great.  But in a clone of Chart.Zoom.js this just brings up a blank page.  I suspect it's because the repo doesn't contain the paths to ../node_modules/....  I'm guessing I'm just missing a part of the setup.  What's the proper way to get the missing content in ../node_modules/?  Should I copy the Chart/hammer content into node_modules/ manually? Is there supposed to be a submodule configuration I'm unaware of?

Thanks!

**Comment by etimberg** [comment]
@ddj116 run `npm install`

**Comment by ddj116** [comment]
Thanks buddy :)

**Comment by jvolf-zolo** [comment]
Love this feature, but I'm having a problem with resetZoom().  When I call that the chart resets, but then the page also reloads.  Is there a way to prevent that?

**Comment by compwright** [comment]
@jvolf-zolo please submit bug reports as new issues, and preferably include a codepen or something where we can see and reproduce the issue. Thanks!
