### ISSUE TITLE
panning problem

### ISSUE THREAD

**Issue by alessandroperetti** [chartjs/chartjs-plugin-zoom#109]
Hi,

i am using the zoom chart plugin. In my sample I have 8 points inside the chart. The zoom in x and y axis is working well but the panning no. Specifically, when I click for panning the chart zooms (for no reasons) between two points and the panning is working between two points.  What's the problem? How can i solve this?

Alessandro

**Comment by mcelotti** [comment]
Hi Alessandro,
after some debugging I've forked the repo (https://github.com/mcelotti/chartjs-plugin-zoom) and fixed the issue, I won't make a PR since the solution is just a quick-and-dirty workaround, the real fix requires more work.
I've created a new sample called "zoom-line-xy.html" to show how it works.

Hope this helps,
Marco
