### ISSUE TITLE
[Feature] Time series data sliding window

### ISSUE THREAD

**Issue by Hideman85** [chartjs/chartjs-plugin-zoom#160]
I would like to display routing info on long period. And your zoom in x axis is very useful but we cant easily move view to another part of chart.
I request addition of the same chart (simplify or not) but smaller than the reel chart use for moving sliding window.

Like this example:
![image](https://user-images.githubusercontent.com/16165119/43892577-9a9d1966-9bcc-11e8-9c33-09d0f8a3a2be.png)
Maybe with x axis simplified (each hours / days / week (maybe user configurable))  and y axis hidden.

**Comment by guilhermecgs** [comment]
very such needed!

**Comment by Techn1x** [comment]
I would also find this very useful, but I question whether it's in the scope of this plugin.

It could be done manually by creating a second (smaller) chart, beneath your detailed chart.

Detailed chart:
* onZoom() or onPan() called - get the new scale min/max from the chart instance (you might need this PR https://github.com/chartjs/chartjs-plugin-zoom/pull/178 ) and apply these values to change the highlighted section of the smaller chart (probably by modifying an annotation)

Smaller chart:
* Contains downsampled data
* Contains an annotation for the highlighted area https://github.com/chartjs/chartjs-plugin-annotation
* Set the rangeMin and rangeMax for both zoom & pan for the chart to be the same width as the entire chart - so that it is rigid and does not move.
* onPan() and onZoom() will still be called, which should contain data on how it was panned or zoomed (if you use my PR) - this can then be used to modify the annotation and set the new min/max on the detailed chart

**Comment by etimberg** [comment]
Agreeing with the last comment here, this is outside the scope of this plugin at this time.

**Comment by tlmader** [comment]
> I would also find this very useful, but I question whether it's in the scope of this plugin.
> 
> It could be done manually by creating a second (smaller) chart, beneath your detailed chart.
> 
> Detailed chart:
> 
> * onZoom() or onPan() called - get the new scale min/max from the chart instance (you might need this PR [Added onPan/onZoom args #178](https://github.com/chartjs/chartjs-plugin-zoom/pull/178) ) and apply these values to change the highlighted section of the smaller chart (probably by modifying an annotation)
> 
> Smaller chart:
> 
> * Contains downsampled data
> * Contains an annotation for the highlighted area https://github.com/chartjs/chartjs-plugin-annotation
> * Set the rangeMin and rangeMax for both zoom & pan for the chart to be the same width as the entire chart - so that it is rigid and does not move.
> * onPan() and onZoom() will still be called, which should contain data on how it was panned or zoomed (if you use my PR) - this can then be used to modify the annotation and set the new min/max on the detailed chart

Do you have a code sample of how this could be done? 🙂
