### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by jledentu** [chartjs/chartjs-plugin-zoom#191]
Hi,

I think it would be nice to add some tests on this library. I can see two types of tests:

- **Unit tests** to test programmatically the behaviour of helper methods. I recommend using Karma (for testing in a real browser) + Jest (actively maintained, have nice mocking features and provides a good developer experience). These tests are partial and don't allow to test the generated canvas images.
- **Visual regression tests** would allow to check the whole behaviour of the plugin by comparing generated images with reference images. [https://github.com/americanexpress/jest-image-snapshot](jest-image-snapshot) sounds good, but I haven't tested it yet. Other tools like [BackdropJS](https://github.com/garris/BackstopJS) are powerful but a bit more complex to add on a CI.

As a first iteration, I suggest to create a PR adding Karma + Jest + basic unit tests. What do you think @benmccann?

**Comment by benmccann** [comment]
I would try to match the tools used in the main https://github.com/chartjs/Chart.js repo as much as possible for consistency. We try to keep things consistent so that people can easily jump between contributing on the different chart.js plugins without having to learn new stuff. I know the upstream uses karma. I believe they have a solution for visual regression tests too, but haven't learned that part. I'm not sure if they have a mocking solution. I'd ask in the #dev Slack channel for Chart.js (I see you just joined. Yay!) about the visual regression and mocking to see what if anything is being used first to make sure we don't adopt something different here in case they already have a solution in place

**Comment by jledentu** [comment]
I started to work on this issue a few months ago, but this requires more time than I can really spend on this project. I suggest to push a PR that only sets up the tools, folders, etc for running tests. Future PRs would bring effective tests in order to increase the code coverage progressively? That will also make the reviews easier.

**Comment by benmccann** [comment]
Yeah, I don't think we have to add all tests at once. Adding one test in the PR where we setup the tools, etc. would be nice to verify that they work

**Comment by jledentu** [comment]
* Tests had been set up
* More tests have been written since then
* Code coverage is displayed and is increasing progressively

I think we can close this issue.
