### ISSUE TITLE
Removing clipping side-effect : 'bubble' dataset displayed outside the chart area

### ISSUE THREAD

**Issue by Lekishor** [chartjs/chartjs-plugin-zoom#274]
![bubble_no_clip](https://user-images.githubusercontent.com/49158077/65694854-cd802180-e076-11e9-8c6c-f0071a449294.png)

As shown above, when using pan / zoom on a line graph with a dataset requested to be displayed as 'bubble' type we can see that those bubbles are still displayed when they are moving outside the "chart area".

I looked at the different tickets(e.g. #177 ) that lead to the removal of the clipping so I understand why it was done but this is a side effect of this.
The information is a bit late I know this would have been better found out to answer #249 prior to merging it :)

Not sure why bubbles aren't handle the same way as other elements by chartjs though.

Here is a simple example to reproduce this behaviour.
https://codepen.io/Lekishor/pen/dybLXoQ
Chartjs 2.8.0
Zoom 0.7.4

**Comment by benmccann** [comment]
I wanted to add one clarification for anyone else who reads this. The codepen is for a `'line'` chart and not a `'bubble'` chart, which is a distinct chart type in Chart.js

**Comment by benmccann** [comment]
@Lekishor thank you for reporting this. This appears to be a bug in the main Chart.js library because I can get poor behavior even without using the zoom plugin. I think if we fix it there that would be best because then we would not experience the negative side effects that clipping was causing

I've filed a new issue to track this in the main Chart.js library https://github.com/chartjs/Chart.js/issues/6540. I'm not sure I have time to address it myself, but if you'd like to try fixing it, let me know and we can discuss the best way to go about it and I will help review any PR

**Comment by benmccann** [comment]
It's actually probably just a couple lines to fix. I added details to the Chart.js bug report. The main thing would just be testing the fix and writing a unit test

**Comment by Lekishor** [comment]
Thanks for the quick answer @benmccann !

I guess I should have reported it directly to the chartjs project then but I did not thought of testing as you did by removing zoom and tweaking the tick values so it seemed a good idea to attach this to the no-clipping recently merged. My bad!

I did not had time to dive into chartjs as I did into the zoom plugin yet but if I can find the time to do so I'll start by working on this issue :)

**Comment by benmccann** [comment]
I've sent a PR to the main Chart.js repo to fix this

**Comment by benmccann** [comment]
Nevermind. My fix didn't quite work. I don't think I have time to fix this since it's a little more involved than I originally hoped
