### ISSUE TITLE
Live Codepen demo not working

### ISSUE THREAD

**Issue by TheZephyr** [chartjs/chartjs-plugin-zoom#303]
I wanted to implement this plugin in my project but I can't get it to work using default options from readme, so I checked out the live demo (https://codepen.io/jledentu/pen/NWWZryv), but it doesn't work .

Is it just me or for everyone? The previous one (https://codepen.io/anon/pen/PGabEK) works as intended, but I think it doesn't help me with the latest version of the plugin.

**Comment by benmccann** [comment]
@jledentu it looks like the codepen updated in https://github.com/chartjs/chartjs-plugin-zoom/pull/301 might not be the right one. It doesn't look like it uses the zoom plugin, but uses the datalabels plugin instead. Sorry I should have reviewed more closely and caught before merging. Do you have another link we can use to update it to?

**Comment by TheZephyr** [comment]
Well, that's the actual problem that I personally have - I can't get neither zoom nor pan to work in my project, hence the question, so I can't provide any working solution at the moment, sorry. Maybe someone else can update it in the meantime (I hope).

**Comment by jledentu** [comment]
Oops, my bad, I'm so sorry. Actually, @benmccann, it's totally my fault, because the codepen was OK when you reviewed the PR. But since, I reused the pen to test something else, and the pen was auto-saved before I forked it! I didn't know that Autosave was enabled by defaut on Codepen, I disabled this options so it should be ok now.

I restored the Codepen. @TheZephyr can you test again? Thanks.

**Comment by TheZephyr** [comment]
All good now. Thank you for quick response.
