### ISSUE TITLE
Zooming too much freezes page

### ISSUE THREAD

**Issue by filips123** [chartjs/chartjs-plugin-zoom#320]
Zooming into chart too much freezes the whole page in Firefox. I tested this with zoom time sample.

I tested this with Firefox 74 and versions of libraries that are provided in the sample page. It's not reproducible in Chrome. In Chrome, the chart just gets messed up and eventually restores original zoom.

**Comment by jledentu** [comment]
I can't reproduce the freezing you describe. But I reproduce the original zoom restored. It happens when `min` and `max` are so closed that they become equal, so the diff is `0` and a division by 0 makes the next zoom mess up.

We could fix it by checking `range !== 0` in the `zoomNumericalScale` function, but a more generic approach would be to implement configuration of maximal zoom step, i.e the minimal distance between `min` and `max`.
