### ISSUE TITLE
Panning through scrollbar

### ISSUE THREAD

**Issue by anubhavng** [chartjs/chartjs-plugin-zoom#383]
Can we have a option to pan using a horizontal scroll bar in case of X axis Zoom? Sometimes end user might not be aware of the panning option without the scroll bar.

**Comment by farrukhrashid1997** [comment]
Hey there anubhavng,

I am using react with this plugin and was faced with the same requirement. As of now there are is no official way to achieve this requirement. But, I have a workaround. 

```
scales: {
      xAxes: [
        {
          display: false,
          gridLines: {
            display: false
          },
          ticks: {
            max: monthLabels[maxMonth],
            min: monthLabels[maxMonth - 5]
          }
        }
      ],

```

In the above code, I have set the minimum and maximum ticks. The maxMonth changes on pressing a button, and the line chart pans to the right/left, since the max and min are changing. 

Let me know if I can be of anymore help.

**Comment by farrukhrashid1997** [comment]
@anubhavng please close this issue if you are satisfied with the answer.

**Comment by benmccann** [comment]
We won't be building any UI since there are an infinite number of control and styling options people may want

**Comment by jcorevnue2022** [comment]
I know it's closed but is there anyone who had a workaround to show scrollbar?
