### ISSUE TITLE
Tick labels can overlap when chart is panned

### ISSUE THREAD

**Issue by jachstet-sea** [chartjs/chartjs-plugin-zoom#4]
(split from #2 as a separate issue)

When a graph is dragged, the tick labels can overlap:
![curved](https://cloud.githubusercontent.com/assets/7993508/15071553/d2afd7f0-138c-11e6-94a1-90b54335cd72.png)

This is due to the tick min and max values beeing overriden and the first and last tick always beeing displayed.

**Comment by josefpaij** [comment]
Bump

**Comment by skhan02** [comment]
@jachstet-sea , @josefpaij  were you able to resolve this issue? I have the same issue where the ticks are overlapping. See below. Thanks in advance for the insight!
![Screen Shot 2019-05-18 at 6 23 10 PM](https://user-images.githubusercontent.com/3004036/57976682-b92a6a80-799a-11e9-855b-df655e462fc7.png)

**Comment by benmccann** [comment]
Please file this as a bug in https://github.com/chartjs/Chart.js. This plugin doesn't draw the scales, so we won't be able to fix it here. Sorry for the inconvenience of having to refile the bug. Github doesn't have a built-in way of moving issues to other projects

**Comment by benmccann** [comment]
I think this is an issue when you try to zoom out beyond the range of the data. I'll investigate and see if I can find what happens

**Comment by benmccann** [comment]
I figured out what happens here in when `distribution: 'series'` and `source: 'auto'`. If you zoom out a lot, the max set by the zoom plugin will be far away from the max data point in terms of time, but only one data point away in terms of the data in the timestamp lookup table. That's what results in them overlapping. This will be fixed by the rewrite of the auto-skipper. I originally submitted that as https://github.com/chartjs/Chart.js/pull/6274, but hit some performance problems. I have those problems solved and will resubmit it once my pending PRs are merged

I'll reopen this issue to track as a reminder to test again after I get those changes in

**Comment by benmccann** [comment]
Also, I was able to fix this by setting `rangeMin` and `rangeMax` to the min and max data values. I wonder if this should be done by default.

```
        const data = this.props.data.datasets[0].data;
        .
        .
        .
        plugins: {
          zoom: {
            zoom: {
              enabled: true,
              mode: 'x',
              rangeMin: {
            	x: data[0].x
              },
              rangeMax: {
              	x: data[data.length - 1].x
              }
            }
          }
        }
```

**Comment by etimberg** [comment]
This appears resolved with Chart.js v3 and 1.0.1-beta.1 of the zoom plugin

![zoom edges](https://user-images.githubusercontent.com/6757853/115998918-a7569680-a5b7-11eb-9f10-ba27db405353.gif)
