### ISSUE TITLE
chartjs-plugin-zoom can't get imported in svelte ?

### ISSUE THREAD

**Issue by simcolin** [chartjs/chartjs-plugin-zoom#491]
It looks like I can't manage to import the plugin when I use it with **Svelte** , here is a example if you want to test :

[Bug proof chart.js zoom plugin](https://svelte.dev/repl/ab37d4d1f3a14f53971ac51cac380dc0?version=3.38.1)

Here are my packages and versions :
![image](https://user-images.githubusercontent.com/32394815/116899048-64d82e00-ac37-11eb-8345-a7a47dd151d1.png)

**Edit :**
Here is the error I get in my local project when I import 'chartjs-plugin-zoom' (little different than Svelte REPL error)
![image](https://user-images.githubusercontent.com/32394815/116899539-f3e54600-ac37-11eb-823a-47e2a5e04b84.png)

**Comment by kurkle** [comment]
Need a pre-release (1.0.0-beta.5) with chart.js 3

**Comment by simcolin** [comment]
@kurkle thanks, that fixed my problem.
But I have so point that I haven't seen this documented anywhere, I might have searched to wrong place. Even the chartjs-zoom-documentation says it works for chartjs >= 3.0.0 but without explaining that it needs beta version => https://www.chartjs.org/chartjs-plugin-zoom/guide/

**Comment by kurkle** [comment]
Fair enough. There is this tip though:

![image](https://user-images.githubusercontent.com/27971921/116908004-0fa61780-ac4b-11eb-887c-0ced01dba5f8.png)

Further documentaion about the need for beta is just not there, because we are still in the time/space of chart.js v3 beta releases and just fallen a little behind with a full release. You can expect it soon, and thus I'm not in favor of documenting the current state.

**Comment by simcolin** [comment]
You've got a point, thanks for the explanation and the help. Looking forward to see the next release.

**Comment by kurkle** [comment]
Duplicate of #447
