### ISSUE TITLE
Zoom speed?

### ISSUE THREAD

**Issue by vzelenko** [chartjs/chartjs-plugin-zoom#50]
Hi, I have tried varying Zoom sensitivity value from 10 (very slow) to 0.0001 (pretty fast) but it seems that the dataset is Zoomed in 1 data point at a time.

Is there any way to control the 'step' of zoom function?

Thanks for any help.

**Comment by etimberg** [comment]
@vzelenko this is not currently possible

**Comment by srv91** [comment]
+1
When dealing with a huge set of datapoints, I think having to increase the 'step' of zoom will be helpful.

**Comment by miguel550** [comment]
+1

**Comment by honcumilan** [comment]
+1

**Comment by fbc** [comment]
+1

**Comment by gregpaton08** [comment]
+1

**Comment by jledentu** [comment]
@benmccann I suggest to add a `speed` property that handles the coefficient of zoom by wheel:

```js
zoom: {
  enabled: true,
  mode: 'xy',
  sensitivity: 3,
  speed: 10 // would be a percentage
}
```

**Comment by ThinkerBell1** [comment]
@jledentu - 
The sensitivity option is exactly what i was looking for. I have a large set of data (8,000 points) and it take ages to zoomIn..
i tried using it as you suggest above but it doesn't completely work..
Can you add a link to a working example?
[I tried this](https://codepen.io/thinkerBell/pen/ZNNwWV)
I also suggest adding an example to readme because there is no documentation about it..

**Comment by koba-1** [comment]
> @jledentu -
> The sensitivity option is exactly what i was looking for. I have a large set of data (8,000 points) and it take ages to zoomIn..
> i tried using it as you suggest above but it doesn't completely work..
> Can you add a link to a working example?
> [I tried this](https://codepen.io/thinkerBell/pen/ZNNwWV)
> I also suggest adding an example to readme because there is no documentation about it..

I have the same issue, is anyone able to make this work?

**Comment by ferreria23** [comment]
> @jledentu -
> The sensitivity option is exactly what i was looking for. I have a large set of data (8,000 points) and it take ages to zoomIn..
> i tried using it as you suggest above but it doesn't completely work..
> Can you add a link to a working example?
> [I tried this](https://codepen.io/thinkerBell/pen/ZNNwWV)
> I also suggest adding an example to readme because there is no documentation about it..

Same issue here, any updated information about this issue?

**Comment by ghoulboy** [comment]
me too

**Comment by ShengHow95** [comment]
Similar issues here. Very slow in zooming and panning. Any updates?

**Comment by camilotabaresj** [comment]
me too

**Comment by danhk0612** [comment]
I have a same issue

**Comment by benmccann** [comment]
Saying me too on a closed bug with no extra info doesn't help much. I'd recommend filing a new issue with more info:
* What version of chart.js?
* Have you tried the `speed` and `sensitivity` options?
* What axis type?
* What is happening vs what do you expect?
* Provide an interactive example on a site like plunker

**Comment by yoelz55** [comment]
Hi, and good evening,

I have the same issue.

- **What version of the plugin and chart.js?**
The last one

- **Have you tried the speed and sensitivity options?**
Yes, it almost doesn't help

- **What axis type?**
x-axis

- **What is happening vs what do you expect?**
The zoom on the y-axis works perfectly but the x-axis doesn't work when the mouse cursor while zooming is on the left side and when the cursor is on the right side it does the zoom but really slow.
I tried the zoom by dragging the rectangle, unfortunately, I got the same result, the x-axis didn't work but the y-axis worked fine.

- **Provide an interactive example on a site like plunker**
[https://codepen.io/yoelz55/pen/WNQLxRN](https://codepen.io/yoelz55/pen/WNQLxRN)

Thank you in advance for any help,
Yoel

**Comment by mikhailtsai** [comment]
Hi there! I have everything the same like @yoelz55 have.

**Comment by kalahiri** [comment]
My solution to this problem is to take the unminified source code and adjust the zooming step size. Because the step size is hardcoded, there is no other way to set this. 

I have a standard chart with type = 'bar'. Zooming using the mouse wheel gets you in the function zoomCategoryScale();. For other types of charts you could end up using one of the other zoomXxxxScale(); functions. 

The goal of that function is to determine the new min index and max index of the range for the chart. Depending on the direction of your turning the mouse wheel, the min index gets +1 or -1. These +1 and -1 are hardcoded in the plugin, but you can change them of course or use a variable so it becomes configurable using the zoomOptions. 

If you change this step size to, let's say 10, the charts zooming is done by 10 ticks instead of 1 tick on the x-as at each turn of the mouse wheel. You can set it by any vale you like, of course.
