### ISSUE TITLE
wheel movement needed after enabling drag programmatically (zoom plugin 1.0.1)

### ISSUE THREAD

**Issue by pmbert** [chartjs/chartjs-plugin-zoom#532]
After enabling drag programmatically, it needs an additional wheel movement to get dragging work:

- start chart with zoom.enabled=true and drag.enabled=false.
> zoom is working and drag not (of course)
- now set drag.enabled=true.
> but no reaction when moving the mouse
- moving mouse wheel
> now drag is working as espected

**Comment by kurkle** [comment]
Did you call `chart.update()` after setting drag.enabled to true?

**Comment by pmbert** [comment]
Yes, I do that as a workaround.
It's necessary to do that in both direction: drag.enabled to true and drag.enabled to false.

**Comment by kurkle** [comment]
That is because the event listener config is only changed in update. Plugin does not listen for mousedown if the drag mode is not enabled.
This could be worked around, but it would be a compromise to consume more resources for every event and/or listen to more events than needed for the active config.

With chart.js its common to require update for changes to take effect, so I would not consider this a bug.

**Comment by pmbert** [comment]
Thank you for clarification.
