### ISSUE TITLE
Chrome warning - Added non-passive event listener to a scroll-blocking 

### ISSUE THREAD

**Issue by alxAgu** [chartjs/chartjs-plugin-zoom#597]
I'm getting hundreds of warnings in Chrome. Using `chart.js v3.6.0` and  `chartjs-plugin-zoom v1.2.0`.

```
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
```

![chrome-warnings](https://user-images.githubusercontent.com/2165454/142361502-bdbbc91f-7fdc-4521-8633-53c0cd1288bc.png)

![code](https://user-images.githubusercontent.com/2165454/142361597-252a7c30-ed96-4104-b079-a2e98e708f4e.png)

We might need a `passive: true` there. Is anyone else getting this warnings?

**Comment by kurkle** [comment]
Chrome gives those warnings for me too. But we can not use `passive: true`, because we need prevent the page from scrolling under the chart.

From: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

>passive
A boolean value that, if true, indicates that the function specified by listener will never call preventDefault(). If a passive listener does call preventDefault(), the user agent will do nothing other than generate a console warning. See Improving scrolling performance with passive listeners to learn more.

And here we are using the `preventDefault()` that passive listeners do not call:

https://github.com/chartjs/chartjs-plugin-zoom/blob/b1d22454e67861174a147ff87e2ad77d50b13684/src/handlers.js#L131-L134

**Comment by kurkle** [comment]
What we could do about this, is detect the changes in listener configuration and only re-attach the listeners when needed. This would reduce the warning count.
