### ISSUE TITLE
Page not loading when plugin options undefined

### ISSUE THREAD

**Issue by andig** [chartjs/chartjs-plugin-zoom#96]
After including the plugin my chart stops to load:

	jquery-3.1.1.min.js:2 jQuery.Deferred exception: Cannot read property 'enabled' of undefined TypeError: Cannot read property 'enabled' of undefined
	    at Object.beforeInit (http://localhost:8000/vz/htdocs/vendor/chartjs/chartjs-plugin-zoom.js:377:26)

Which is:

		} else if (options.zoom.enabled) {
			chartInstance.zoom._wheelHandler = function(event) {
				var rect = event.target.getBoundingClientRect();
				var offsetX = event.clientX - rect.left;
				var offsetY = event.clientY - rect.top;

Seems its missing a test if `options.zoom` is defined?

**Comment by AhmedBHameed** [comment]
Hi @andig 

I'd like to help you since i use this plugins with no problems.
How did you configure your options including zoom option ? can you show us the fully configuration of the chart ?
Because it seems you did not add the library properly OR the configuration missing some stuff.
Waiting your answer.
